### PR TITLE
Update fig1 notebook & qzvs

### PR DESCRIPTION
**Pull request by gibsramen**
Generated with Empress commit 65b3f0176097bba372364aa37931c63549bc21d8

### CODE REVIEW

**Review by ElDeveloper — APPROVED** [review]
@gibsramen can you also update the README with the new instructions? Otherwise looks good to merge, thanks!

**Comment by gibsramen** [comment]
Sure thing. Did we update the units of the barplot length since the original visualization was generated? 500 seems way too large. If so I'll need to update both 1a & 1b instructions with the new lengths we choose.

**Comment by fedarko** [comment]
Yeah, I think we increased default barplot lengths in the circular layout a few months back. The default lengths should work well for more cases, so it might (your call) be possible to just not have the user adjust the lengths at all any more.

**Comment by gibsramen** [comment]
Got it. @ElDeveloper is this length of barplot (150) okay? If so I'll update the text accordingly.

image

**Comment by ElDeveloper** [comment]
Yes, that looks great!

**Pull request merged**
