### PR TITLE
figure 2a

### PR DESCRIPTION
**Pull request by kwcantrell**

### CODE REVIEW

**Comment by fedarko** [comment]
This looks great, thanks @kwcantrell!

One question: is there a reason that the encodings go as follows:

> Note: No significant differnce = -1, Lower in COVID-19 samples = 0, Higher in COVID-19 samples = 1

It seems to me like it might be more intuitive to encode "Lower in COVID-19 samples" as -1, and to encode "No significant difference" as 0. I suspect if we did this, and used a Diverging color map to encode the two barplot fields, this figure might look even prettier - since now all of the "No significant difference" values (which make up most of the values in the barplots) would be represented as the midpoint of the colormap (which for most of the diverging color maps is white or some other light color), while the "Lower in COVID" and "Higher in COVID" would be visually emphasized.

For reference, here's what using the diverging Red-Blue color map looks like with the current figure:

cov

The barplots appear mostly dark red due to all of the -1s, indicating no significant difference for these features. If we swapped -1 and 0 as proposed above, then now most of the colors in the barplots would be a neutral white-ish color, leaving dark red for the "lower in COVID" features (and dark blue for the "higher in COVID" features).

**Comment by kwcantrell** [comment]
I chose that particular encoding because it made the orange-red color map work. After a discussion with Niina and Kristen, we settled on this color map because covid dominate features are colored with a dark red color and non covid dominate features are color with a light color. Essentially this color map was the best one that visually separated the different groups. 

I agree that your suggested encoding makes more sense. In fact I used that encode with original figure using the spectral color map. But Niina pointed out that it is a bit difficult see the difference in the two groups in the current figure. So we settled on the Orange-Red color map because we have one dark color and one light color. However, the current master branch does not have the ability to switch colors so I had to modify the encoding in order to get the colors I wanted. In the final figure for the paper, we will change the legend in illustrator and replace -1 with "No significant difference" and so on.

**Comment by fedarko** [comment]
That is fair. I can understand that reasoning.

So for reference, the current figure I get from following the instructions and using the dataset with the current encodings is:

image

However, I still think that switching -1 and 0 might look better. Even if we still use the Orange-Red color map, the switched encodings look like:

stuff

All three levels are still distinguishable -- but I think I actually prefer this because the "lower" features are colored as lighter than the "no significant difference" features. There is directionality between all three categories that I think using the switched encodings makes clearer, even if the reader will never see the -1/0/1 assignments.

If the "middle orange" color is too overwhelming, we could also use another sequential color map, for example Viridis, Greys, or Purples:

viridis
(Yellow being the "high" color for this map works really well to emphasize the "these are higher in COVID!" features)

gresa


purp2
(Matches a similar barplot layer in Fig. 2C that also uses purples to show numeric data)

I agree that spectral looks kinda gross for the barplots in this figure, because distinguishing the high and low colors is difficult:

spectr

Pink-Yellow-Green might help, but it's still kind of hard to pick things out.

piyg

IDK -- This figure is fine as is, but I can't help but feel like using one of the other options here with the switched color map (e.g. Viridis) might make the figure easier to understand. It's ultimately not my call (and I guess this will stop being an issue as soon as we get color-changing integrated in EMPress :), but I think this might make things even clearer.

**Comment by kwcantrell** [comment]
One of the reasons we settled on the orange-red was because "higher in covid" was assigned red (which typically symbolizes a "bad" value).

However, I do like the Viridis color map. Plus we would be able to use an encoding that logically makes more sense. @ElDeveloper do you think the turquoise color for "no significant difference" would be to overwhelming? 

As a side note, I am not a big fan of representing "lower in covid" as white because to me white represents features that don't have data associated with them or data that is not relevant i.e. "no significant change".

**Comment by ElDeveloper** [comment]
@kwcantrell @fedarko thanks for sharing these. I think viridis makes sense, specially since we the color encoding is more natural that way.

**Comment by kwcantrell** [comment]
thanks @ElDeveloper and @fedarko. I updated the encoding scheme and readme to use Viridis

**Review by ElDeveloper — APPROVED** [review]

**Comment by ElDeveloper** [comment]
Thanks so much @kwcantrell

**Pull request merged**
